# making Glass with Python
print('    *')
print('   * *')
print('  * * *')
print(' * * * *')
print('* * * * *')
print('* * * * *')
print('* * * * *')
print('* * * * *')
print('* * * * *')
print('* * * * *')
print(' * * * *')
print('  * * * ')
print('   * *')
print('    * ')
print('    * ')
print('    * ')
print('* * * * *')
print('* * * * * ')
